CREATE TABLE INSTRUCTOR_MST (
  INSTRUCTOR_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  ACTIVE_FLAG int(11) NOT NULL
);

CREATE TABLE INSTRUCTOR_DTL (
  INSTRUCTOR_DTL_ID int(11) NOT NULL AUTO_INCREMENT,
  INSTRUCTOR_MST_ID int(11) NOT NULL,
  FIRST_NAME varchar(45) NOT NULL,
  LAST_NAME varchar(45) NOT NULL,
  EMAIL varchar(45) NOT NULL,
  YOUTUBE_CHANNEL varchar(128) NOT NULL,
  HOBBY varchar(45) NOT NULL,
  ACTIVE_FLAG int(11) NOT NULL
);

CREATE TABLE COURSE_MST (
  COURSE_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  INSTRUCTOR_MST_ID int(11) NOT NULL,
  ACTIVE_FLAG int(11) NOT NULL
);

CREATE TABLE COURSE_DTL (
  COURSE_DTL_ID int(11) NOT NULL AUTO_INCREMENT,
  COURSE_MST_ID int(11) NOT NULL,
  TITLE varchar(100) NOT NULL,
  COURSE_DESC varchar(200) NOT NULL,
  DURATION int(11) NOT NULL,
  NO_OF_LEC int(11) NOT NULL,
  LEVEL int(11) NOT NULL,
  PRICE int(11) NOT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

CREATE TABLE REVIEW_MST (
  REVIEW_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  COMMENT varchar(256) DEFAULT NULL,
  COURSE_MST_ID int(11) DEFAULT NULL,
  STUDENT_MST_ID int(11) DEFAULT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

CREATE TABLE STUDENT_MST (
  STUDENT_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(45) DEFAULT NULL,
  LAST_NAME varchar(45) DEFAULT NULL,
  EMAIL varchar(45) DEFAULT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

/*
-- join table
CREATE TABLE COURSE_STUDENT(
  COURSE_MST_ID int(11) NOT NULL,
  STUDENT_MST_ID int(11) NOT NULL
);
*/