CREATE TABLE INSTRUCTOR_MST (
  INSTRUCTOR_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(45) DEFAULT NULL,
  LAST_NAME varchar(45) DEFAULT NULL,
  EMAIL varchar(45) DEFAULT NULL,
  INSTRUCTOR_DTL_ID int(11) DEFAULT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

CREATE TABLE INSTRUCTOR_DTL (
  INSTRUCTOR_DTL_ID int(11) NOT NULL AUTO_INCREMENT,
  YOUTUBE_CHANNEL varchar(128) DEFAULT NULL,
  HOBBY varchar(45) DEFAULT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

CREATE TABLE COURSE_MST (
  COURSE_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  TITLE varchar(128) DEFAULT NULL,
  INSTRUCTOR_MST_ID int(11) DEFAULT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

CREATE TABLE REVIEW_MST (
  REVIEW_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  COMMENT varchar(256) DEFAULT NULL,
  COURSE_MST_ID int(11) DEFAULT NULL,
  STUDENT_MST_ID int(11) DEFAULT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

CREATE TABLE STUDENT_MST (
  STUDENT_MST_ID int(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(45) DEFAULT NULL,
  LAST_NAME varchar(45) DEFAULT NULL,
  EMAIL varchar(45) DEFAULT NULL,
  ACTIVE_FLAG int(11) DEFAULT NULL
);

/*
-- join table
CREATE TABLE COURSE_STUDENT(
  COURSE_MST_ID int(11) NOT NULL,
  STUDENT_MST_ID int(11) NOT NULL
);
*/